### ISSUE TITLE
Expected an instance of AppBundle\Entity\Product. Got: Sylius\Component\Core\Model\Product

### ISSUE THREAD

**Issue by h3llr4iser** [bitbag-commerce/CmsPlugin#11]
Hi, you have to change your association in Page.orm.yml, the target entity have to be Sylius\Component\Product\Model\ProductInterface, because if Someone extend product entity your plugin throw this error updating a page.

```
BitBag\CmsPlugin\Entity\Page:
    type: entity
    table: bitbag_cms_page
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        code:
            type: string
            length: 250
        enabled:
            type: boolean
    manyToMany:
        products:
            targetEntity: Sylius\Component\Product\Model\ProductInterface
            joinTable:
                name: bitbag_cms_page_products
                joinColumns:
                    page_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    product_id:
                        referencedColumnName: id
```
